---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeparrot


---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeparrot
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeparrot
subjects:
- kind: ServiceAccount
  name: kubeparrot
  namespace: default
roleRef:
  kind: ClusterRole
  name: kubeparrot
  apiGroup: rbac.authorization.k8s.io
