---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeparrot
  namespace: monitoring

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeparrot
rules:
- apiGroups: [""]
  resources: ["pods","nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeparrot
subjects:
- kind: ServiceAccount
  name: kubeparrot
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: kubeparrot
  apiGroup: rbac.authorization.k8s.io
